const Journey=require('../models/Journey');const Point=require('../models/JourneyLocationPoint');const Route=require('../models/Route');const Hazard=require('../models/Hazard');const {projectToRoute,bearing,angularDiff,haversine}=require('../utils/geo');const {relevantHazards}=require('../services/geofenceService');const {shouldReroute}=require('../services/rerouteService');const {ok}=require('../utils/response');
const blockageType=t=>/(block|closure|closed|construction|stopped vehicle)/i.test(String(t||''));
exports.update=async(req,res)=>{
  const j=await Journey.findOne({_id:req.body.journeyId,userId:req.user._id});if(!j)return res.status(404).json({success:false,message:'Journey not found'});if(j.status!=='ACTIVE')return res.status(409).json({success:false,message:`Journey is ${String(j.status||'not active').toLowerCase()}; tracking requires an active journey`});
  const p={lat:Number(req.body.lat),lng:Number(req.body.lng)};if(!Number.isFinite(p.lat)||!Number.isFinite(p.lng))return res.status(422).json({success:false,message:'Valid lat/lng required'});
  await Point.create({journeyId:j._id,userId:req.user._id,location:{type:'Point',coordinates:[p.lng,p.lat]},accuracy:req.body.accuracy,heading:req.body.heading,speed:req.body.speed,altitude:req.body.altitude,capturedAt:new Date(req.body.timestamp||Date.now())});
  let result={distanceCovered:j.distanceCovered||0,distanceRemaining:j.distanceRemaining??j.totalDistance??0,progress:0,etaSeconds:0,alerts:[]};const route=j.routeId?await Route.findById(j.routeId):null;
  if(route?.coordinates?.length){const proj=projectToRoute(p,route.coordinates);const offset=Math.max(0,Number(j.distanceOffset)||0);result.routeDistanceCovered=proj.distanceAlong;result.distanceCovered=offset+proj.distanceAlong;result.distanceRemaining=Math.max(0,proj.total-proj.distanceAlong);result.totalDistance=offset+proj.total;result.progress=result.totalDistance?100*result.distanceCovered/result.totalDistance:0;result.etaSeconds=(route.trafficDuration||route.baseDuration||0)*(proj.total?result.distanceRemaining/proj.total:0);j.totalDistance=result.totalDistance;j.distanceCovered=result.distanceCovered;j.distanceRemaining=result.distanceRemaining;
    let docs=[];try{docs=await Hazard.find({status:'VERIFIED',expiresAt:{$gt:new Date()}}).lean()}catch{}
    result.alerts=relevantHazards(p,route.coordinates,docs,{heading:req.body.heading}).slice(0,5).map(x=>({hazardId:x.hazard._id,type:x.hazard.type,risk:x.hazard.snnRiskLevel,riskScore:x.hazard.snnRiskScore,trustScore:x.hazard.trustScore,distanceAhead:Math.round(x.distanceAhead),confidence:x.hazard.confidence}));
    const critical=result.alerts.some(a=>a.risk==='CRITICAL');const verifiedBlockage=result.alerts.some(a=>blockageType(a.type)&&(a.trustScore??0)>=.55);const currentRisk=Math.max(0,...result.alerts.map(a=>Number(a.riskScore)||0));const safetyDrop=Math.max(0,currentRisk-(Number(route.risk)||0));
    const segA=route.coordinates[Math.min(proj.index,route.coordinates.length-2)],segB=route.coordinates[Math.min(proj.index+1,route.coordinates.length-1)];const expectedHeading=segA&&segB?bearing(segA,segB):null;const headingDifference=angularDiff(req.body.heading,expectedHeading);const accuracy=Math.max(0,Number(req.body.accuracy)||0),speed=Math.max(0,Number(req.body.speed)||0),outsideThreshold=Math.max(40,accuracy*2);const outside=proj.distanceFromRoute>outsideThreshold;if(outside&&!j.offRouteSince)j.offRouteSince=new Date();if(!outside)j.offRouteSince=null;const outsideSeconds=j.offRouteSince?(Date.now()-j.offRouteSince.getTime())/1000:0;const significantDeviation=outside&&(proj.distanceFromRoute>120||outsideSeconds>10)&&(speed<2?outsideSeconds>15:headingDifference>35||proj.distanceFromRoute>80);j.lastDeviationMeters=proj.distanceFromRoute;result.deviation={distanceMeters:proj.distanceFromRoute,accuracy,headingDifference,speed,timeOutsideSeconds:outsideSeconds,significant:significantDeviation};
    result.rerouteRecommendation=shouldReroute(String(j._id),{criticalObstacle:critical,verifiedBlockage,severeTraffic:route.trafficSeverity==='SEVERE',deviationMeters:significantDeviation?proj.distanceFromRoute:0,safetyDrop});
    result.traffic={severity:route.trafficSeverity||'UNKNOWN',mode:route.trafficMode||'unknown',delay:route.trafficDelay||0,provider:route.trafficProvider||null};result.safetyScore=Math.max(0,100*(1-Math.max(Number(route.risk)||0,currentRisk)));const destinationDistance=j.destination&&Number.isFinite(Number(j.destination.lat))&&Number.isFinite(Number(j.destination.lng))?haversine(p,{lat:Number(j.destination.lat),lng:Number(j.destination.lng)}):null;const arrivalThreshold=Math.max(20,Math.min(50,(Number(req.body.accuracy)||10)*1.5));result.arrival={distanceMeters:destinationDistance,thresholdMeters:arrivalThreshold,arrived:Number.isFinite(destinationDistance)&&destinationDistance<=arrivalThreshold&&result.distanceRemaining<=Math.max(60,arrivalThreshold*2)};
    if(route.steps?.length){const next=route.steps.map((step,index)=>{const loc=step.maneuver?.location;const rp=loc?projectToRoute({lat:loc[1],lng:loc[0]},route.coordinates):null;return {step,index,distanceAhead:rp?rp.distanceAlong-proj.distanceAlong:Infinity}}).filter(x=>x.distanceAhead>=-10).sort((a,b)=>a.distanceAhead-b.distanceAhead)[0];if(next){result.nextManeuver={index:next.index,maneuver:next.step.maneuver,name:next.step.name||next.step.maneuver?.name||'',distance:Math.max(0,Math.round(next.distanceAhead))};if(next.distanceAhead<450){const action=next.step.maneuver?.verbalInstruction||next.step.maneuver?.instruction||[next.step.maneuver?.type,next.step.maneuver?.modifier].filter(Boolean).join(' ');result.voicePrompt=next.step.maneuver?.type==='arrive'?'Destination reached.':`In ${Math.max(20,Math.round(next.distanceAhead/10)*10)} meters, ${action}.`}}}
  }
  j.lastKnownPosition={...p,accuracy:req.body.accuracy,heading:req.body.heading,speed:req.body.speed,timestamp:req.body.timestamp||Date.now()};await j.save();req.app.get('io')?.to(`journey:${j._id}`).emit('journey:location',{journeyId:String(j._id),...result,position:j.lastKnownPosition});if(result.alerts?.length)req.app.get('io')?.to(`journey:${j._id}`).emit('hazard:alerts',result.alerts);ok(res,result)
};
