const r=require('express').Router();
const c=require('../controllers/hazardController');
const {authenticate}=require('../middleware/auth');
const v=require('../validators/domainValidators');
const validate=require('../middleware/validate');
r.use(authenticate);
r.get('/nearby',c.nearby);
r.post('/report',v.hazardReport,validate,c.report);
r.post('/:id/confirm',v.hazardConfirm,validate,c.confirm);
module.exports=r;
